CREATE TABLE IF NOT EXISTS tweets(
    id SERIAL PRIMARY KEY,
    tweet_id VARCHAR(15) NOT NULL,
    tweet_text VARCHAR(300) NOT NULL,
    tweet_timestamp TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);