---
version: "3"

services:
  shikari:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - broker
    volumes:
      - type: volume
        source: ./tmp/db
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

  postgres:
    image: postgres
    restart: always
    hostname: pgdatabase
    container_name: shikari_pgdatabase
    env_file:
      - .env
    ports:
    - "5432:5432"
    volumes:
      - type: volume
        source: ./tmp/db
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    hostname: zookeeper
    container_name: shikari_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.0.0
    hostname: broker
    container_name: shikari_broker
    depends_on:
      - zookeeper
    ports:
    - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR

volumes:
  data:
